name: Python application

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: View directory structure
      run: |
        echo "Directory structure:"
        ls -R

    - name: Run tests
      env:
        PYTHONPATH: .  # Adding the project directory to the PYTHONPATH
      run: |
        pytest
